version: 2

models:
  - name: stg__users
    description: "Cleaned user dimension from theLook ecommerce dataset."
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]

  - name: stg__orders
    description: "Cleaned orders at order header level."
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
      - name: order_status
        tests: [not_null]

  - name: stg__order_items
    description: "Cleaned order items at order-item granularity."
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: order_id
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]

  - name: stg__products
    description: "Cleaned product attributes."
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: product_name
        tests: [not_null]

  - name: stg__inventory_items
    description: "Inventory items with product & distribution center context."
    columns:
      - name: inventory_item_id
        tests: [not_null, unique]
      - name: product_id
        tests: [not_null]

  - name: stg__distribution_centers
    description: "Distribution centers used for fulfillment."
    columns:
      - name: distribution_center_id
        tests: [not_null, unique]
      - name: distribution_center_name
        tests: [not_null]

  - name: stg__events
    description: "User events (sessions, page views, etc.)."
    columns:
      - name: event_id
        tests: [not_null, unique]
      - name: user_id
        tests: []
