version: 2

models:
  - name: dim_customers
    description: "Customer dimension with core attributes and order behavior."
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]

  - name: dim_products
    description: "Product dimension with pricing and distribution center linkage."
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: product_name
        tests: [not_null]

  - name: dim_distribution_centers
    description: "Distribution centers used for shipping inventory."
    columns:
      - name: distribution_center_id
        tests: [not_null, unique]
      - name: distribution_center_name
        tests: [not_null]

  - name: fct_order_items
    description: "Order items fact table at the order-item grain, enriched with product & DC info."
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: order_id
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]

  - name: fct_orders
    description: "Order-level fact table with aggregated item metrics."
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
      - name: order_date
        tests: [not_null]
